controllers:
    resource: '../src/Controller/'
    type: attribute

home:
    path: /
    controller: App\Controller\ClientController::index

client_search:
    path: /client/search
    controller: App\Controller\ClientController::search
